apiVersion: apps/v1
kind: Deployment
metadata:
  name: location-tracker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: location-tracker
  template:
    metadata:
      labels:
        app: location-tracker
    spec:
      containers:
      - name: location-tracker
        image: dockerizzz/location-tracker:latest
        ports:
        - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: location-tracker-service
spec:
  type: NodePort
  selector:
    app: location-tracker
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30003