apiVersion: v1
kind: Service
metadata:
  name: location-tracker-service
spec:
  type: NodePort
  selector:
    app: location-tracker
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 30003